#!/bin/bash --login
#$ -cwd          ## Current directory
#$ -m ea 
#$ -pe mpi-24-ib.pe 48
#$ -M zeyuan.miao@postgrad.manchester.ac.uk

module load apps/binapps/abaqus/2020
module load apps/binapps/abaqus/2020 compilers/intel/17.0.7
# Ensure licenses are available. If not, job will automatically requeue.
. $ABAQUS_HOME/liccheck.sh

PRONAME=`basename $0`
CURPATH=$(cd "$(dirname "$0")"; pwd)
for file in `find . -name "*.inp"`; do
# for file in $CURPATH/*.inp; do 
    M_temp_file=`basename $file .inp`  
    T_temp_file=${M_temp_file/M/T} 
    odb_root=$(dirname $(pwd))/Thermal_inp_files/$T_temp_file.odb
    sed -i "s|Thermal_field_odb_root|$odb_root|g" $M_temp_file.inp
    abq2020 job=$M_temp_file cpus=$NSLOTS interactive
done

